production-assistant/src/java/jpa/entities/Project.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author mitya
 */
@Entity
@Table(name = "project")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Project.findAll", query = "SELECT p FROM Project p"),
    @NamedQuery(name = "Project.findByIdProject", query = "SELECT p FROM Project p WHERE p.idProject = :idProject"),
    @NamedQuery(name = "Project.findByDbegin", query = "SELECT p FROM Project p WHERE p.dbegin = :dbegin"),
    @NamedQuery(name = "Project.findByDend", query = "SELECT p FROM Project p WHERE p.dend = :dend"),
    @NamedQuery(name = "Project.findByComment", query = "SELECT p FROM Project p WHERE p.comment = :comment")})
public class Project implements Serializable, WrappingHaving {

    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "id_project")
    private BigInteger idProject;
    @Basic(optional = false)
    @NotNull
    @Column(name = "dbegin")
    @Temporal(TemporalType.DATE)
    private Date dbegin;
    @Column(name = "dend")
    @Temporal(TemporalType.DATE)
    private Date dend;
    @Size(max = 2147483647)
    @Column(name = "comment")
    private String comment;
    @JoinColumn(name = "id_projectstate", referencedColumnName = "id_projectstate")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Projectstate idProjectstate;
    @JoinColumn(name = "id_executor", referencedColumnName = "id_person")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Person idExecutor;
    @OneToMany(mappedBy = "idProject", fetch = FetchType.LAZY)
    private Collection<Linkage> linkageCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idProject", fetch = FetchType.LAZY)
    private Collection<Wrapping> wrappingCollection;

    public Project() {
    }

    public Project(BigInteger idProject) {
        this.idProject = idProject;
    }

    public Project(BigInteger idProject, Date dbegin) {
        this.idProject = idProject;
        this.dbegin = dbegin;
    }

    public BigInteger getIdProject() {
        return idProject;
    }

    public void setIdProject(BigInteger idProject) {
        this.idProject = idProject;
    }

    public Date getDbegin() {
        return dbegin;
    }

    public void setDbegin(Date dbegin) {
        this.dbegin = dbegin;
    }

    public Date getDend() {
        return dend;
    }

    public void setDend(Date dend) {
        this.dend = dend;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Projectstate getIdProjectstate() {
        return idProjectstate;
    }

    public void setIdProjectstate(Projectstate idProjectstate) {
        this.idProjectstate = idProjectstate;
        if (this.idProjectstate.getCode().equals("ENDED")) {
            this.setDend(new Date());
        } else {
            this.setDend(null);
        }
    }

    public Person getIdExecutor() {
        return idExecutor;
    }

    public void setIdExecutor(Person idExecutor) {
        this.idExecutor = idExecutor;
    }

    @XmlTransient
    public Collection<Linkage> getLinkageCollection() {
        return linkageCollection;
    }

    public void setLinkageCollection(Collection<Linkage> linkageCollection) {
        this.linkageCollection = linkageCollection;

    }

    @Override
    public HashMap<Part, BigInteger> getChildParts() {

        HashMap<Part, BigInteger> listParts = new HashMap<Part, BigInteger>();

        for (Linkage ls : this.getLinkageCollection()) {

            for (Map.Entry<Part, BigInteger> se : ls.getChildParts().entrySet()) {
                listParts.put(se.getKey(), se.getValue().add(listParts.get(se.getKey()) == null ? BigInteger.ZERO : listParts.get(se.getKey())));
            }

        }
        return listParts;
    }

    @Override
    public HashMap<Part, BigInteger> getChildWrappingParts() {
        HashMap<Part, BigInteger> listParts = new HashMap<Part, BigInteger>();

        for (Wrapping wp : this.getWrappingCollection()) {
            for (Wrappingpart wt : wp.getWrappingpartCollection()) {
                listParts.put(wt.getIdPart(), wt.getCountElement().add(listParts.get(wt.getIdPart()) == null ? BigInteger.ZERO : listParts.get(wt.getIdPart())));
            }
        }
        return listParts;
    }

    @XmlTransient
    @Override
    public Collection<Wrapping> getWrappingCollection() {
        return wrappingCollection;
    }

    public void setWrappingCollection(Collection<Wrapping> wrappingCollection) {
        this.wrappingCollection = wrappingCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idProject != null ? idProject.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Project)) {
            return false;
        }
        Project other = (Project) object;
        if ((this.idProject == null && other.idProject != null) || (this.idProject != null && !this.idProject.equals(other.idProject))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Project[ idProject=" + idProject + " ]";
    }

    public Object getWrappingItems() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

production-assistant/src/java/jsf/LinkageController.java
package jsf;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import jpa.entities.Elementlinkage;
import jpa.entities.Linkage;
import jpa.session.ElementlinkageFacade;
import jpa.session.LinkageFacade;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import org.primefaces.context.RequestContext;

@ManagedBean(name = "linkageController")
@ViewScoped
public class LinkageController implements Serializable {

    private Linkage current;
    private DataModel items = null;
    @EJB
    private jpa.session.LinkageFacade ejbFacade;
    @EJB
    private jpa.session.ElementlinkageFacade ejbElementFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private Map<String, Object> parameters;
    private String name;
    private BigInteger idLinkage;
    private Elementlinkage elementLinkageToChange;
    private BigInteger elementCountProcess;

    public BigInteger getElementCountProcess() {
        return elementCountProcess;
    }

    public void setElementCountProcess(BigInteger elementCountProcess) {
        this.elementCountProcess = elementCountProcess;
    }

    public Elementlinkage getElementLinkageToChange() {
        return elementLinkageToChange;
    }

    public void setElementLinkageToChange(Elementlinkage elementLinkageToChange) {
        this.elementLinkageToChange = elementLinkageToChange;
    }

    public BigInteger getIdLinkage() {
        return idLinkage;
    }

    public void setIdLinkage(BigInteger idLinkage) {
        this.idLinkage = idLinkage;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setParameters() {
        this.parameters.put("name", this.name);
        recreateModel();
    }

    public LinkageController() {
        parameters = new HashMap<String, Object>();
        this.parameters.put("name", "-1");
        this.setElementCountProcess(BigInteger.ONE);
    }

    public Linkage getCurrent() {
        if (this.getIdLinkage() != null && current == null) {
            current = getFacade().find(this.getIdLinkage());
        }
        if (current == null) {
            current = new Linkage();
        }
        return current;
    }

    public Linkage getSelected() {
        if (current == null) {
            current = new Linkage();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LinkageFacade getFacade() {
        return ejbFacade;
    }

    private ElementlinkageFacade getElementFacade() {
        return ejbElementFacade;
    }


    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public void prepareSearch() {
        this.parameters.clear();
        this.parameters.put("name", name);
        recreateModel();
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Linkage) getItems().getRowData();
        return "View" + "?idLinkage=" + current.getIdLinkage() + "faces-redirect=true";
    }

    public void prepareCreate() {
        if (current == null || current.getIdLinkage() != null) {
            current = new Linkage();
        }
        RequestContext.getCurrentInstance().execute("editDialogVar.show();");
    }

    public void create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LinkageCreated"));
            recreateModel();
            RequestContext.getCurrentInstance().execute("editDialogVar.hide();");
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    public void prepareEdit() {
        RequestContext.getCurrentInstance().execute("editDialogVar.show();");
    }

    public void update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LinkageUpdated"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    /**
     * Рекурсивное удаление сборки
     *
     * @param idLinkage
     */
    public void destroy(Linkage idLinkage) {
        try {
            for (Elementlinkage em : idLinkage.getElementlinkageCollection()) {
                if (em.getIdSublinkage() != null) {
                    Linkage ed = em.getIdSublinkage();
                    em.setIdSublinkage(null);
                    getElementFacade().edit(em);
                    destroy(ed);
                }
            }
            getFacade().remove(idLinkage);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LinkageDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    public void destroy() {
        current = (Linkage) getItems().getRowData();
        destroy(current);
        recreateModel();
    }

    public DataModel getItems() {
        if (items == null) {
            items = new ListDataModel(getFacade().findByNamedQuery("Linkage.findByCriteria", this.parameters));
        }
        return items;
    }

    public void copyIntoProject(BigInteger iId_Project) {
        Map<String, Object> parameters;
        parameters = new HashMap<String, Object>();
        parameters.put("Id_Project", iId_Project);
        parameters.put("Id_Linkage", ((Linkage) getItems().getRowData()).getIdLinkage());
        getFacade().executeStoredProc("select CopyLinkageIntoProject(#Id_Project, #Id_Linkage)", parameters);
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public void addToLinkage() {

        Linkage selectedLinkage = (Linkage) getItems().getRowData();

        Elementlinkage elementLinkage;
        for (Iterator<Elementlinkage> i = this.getCurrent().getElementlinkageCollection().iterator(); i.hasNext();) {
            elementLinkage = i.next();
            if (elementLinkage.getIdSublinkage() != null
                    && elementLinkage.getIdSublinkage().getIdLinkage().compareTo(selectedLinkage.getIdLinkage()) == 0) {
                elementLinkage.setCountElement(elementLinkage.getCountElement().add(this.getElementCountProcess()));
                selectedLinkage = null;
                break;
            }
        }

        if (selectedLinkage != null) {
            elementLinkage = new Elementlinkage();
            elementLinkage.setIdSublinkage(selectedLinkage);
            elementLinkage.setIdLinkage(this.getCurrent());
            elementLinkage.setCountElement(this.getElementCountProcess());
            ejbElementFacade.create(elementLinkage);
            this.getCurrent().getElementlinkageCollection().add(elementLinkage);
        }

        ejbFacade.edit(this.getCurrent());
    }

    public void removeFromLinkage(Elementlinkage e) {
        current.getElementlinkageCollection().remove(e);
        getElementFacade().remove(e);
    }

    public void prepareChangeNotation(Elementlinkage e) {
        elementLinkageToChange = e;
        RequestContext.getCurrentInstance().execute("editElementLinkage.show();");
    }

    public void changeElementNotation() {
        getElementFacade().edit(elementLinkageToChange);
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);

    }

    @FacesConverter(forClass = LinkageController.class)
    public static class LinkageControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LinkageController controller = (LinkageController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "LinkageController");
            return controller.ejbFacade.find(getKey(value));
        }

        String getKey(String value) {
            String key;
            key = value;
            return key;
        }

        String getStringKey(java.math.BigInteger value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

production-assistant/web/Project-view.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <body>
    <ui:define name="title">
        <h:outputText value="Поиск и создание проектов"></h:outputText>
    </ui:define>
    <ui:composition template="./template.xhtml">
        <ui:define name="content">
            <h:form>  
                <h3>
                    <h:panelGrid columns="2" style="margin-bottom:10px">
                        <h:outputTdext value="Проект:" /> <h:outputText value="#{ProjectsearchController.selected.idProject}" />  
                        <h:outputText value="Фио исполнителя:" /> <h:outputText value="#{ProjectsearchController.selected.fioexecutor}" />  
                        <h:outputText value="Состояние проекта:" /> <h:outputText value="#{ProjectsearchController.selected.projectstatename}" />  
                        <h:outputText value="Дата начала:" /> <h:outputText value="#{ProjectsearchController.selected.dbegin}" />  
                        <h:outputText value="Дата начала:" /> <h:outputText value="#{ProjectsearchController.selected.dbegin}" />  
                        <h:outputText value="Дата завершения:" /> <h:outputText value="#{ProjectsearchController.selected.dend}" />  
                        <h:outputText value="Комментарий:" /> <h:outputText value="#{ProjectsearchController.selected.comment}" />  
                    </h:panelGrid>  
                </h3>
            </h:form>
            <h:form id="formLinkage">
                Элементы проекта
                <p:commandButton id="showDialogButton" type="button" value="Добавить" onclick="dlg.show();" /> 
                <p:dialog header="Добавить сборку в проект" widgetVar="dlg" resizable="false">  
                    <h:form id="form">
                        <h:form id="form1">
                            <p:inputText value="#{LinkageController.name}" />  
                            <p:commandButton  action='#{LinkageController.setParameters}' value='Искать'  update=":formLinkage:form:searchLinkage"/>
                        </h:form>
                        <p:dataTable id="searchLinkage" var="item" value="#{LinkageController.items}" >  
                            <p:column headerText="Наименование сборки">  
                                <h:outputText value="#{item.name}" />  
                            </p:column>     
                            <p:column headerText="Инструкция">  
                                <h:outputText value="#{item.instruction}" />  
                            </p:column>  
                            <p:column headerText="Действия">  
                                <p:commandButton action='#{LinkageController.copyIntoProject(ProjectsearchController.selected.idProject)}' update=":formLinkage:linkageData:linkageItem" value='Скопировать в проект1' />
                            </p:column>  
                        </p:dataTable>  
                        <p:commandButton value="ОК" action="#{ProjectsearchController.refresh}" id="submitButton" update=":formLinkage:linkageData" oncomplete="dlg.hide();"/>  
                    </h:form>
                </p:dialog>
                <h:form id="linkageData" prependId="false">
                    <p:dataTable id="linkageItem" var="linkageItem"  value="#{ProjectsearchController.selected.linkage}">
                        <p:column headerText="Наименование">
                            <h:outputText value="#{linkageItem.name}" />
                        </p:column>
                        <p:column headerText="Инструкция">
                            <h:outputText value="#{linkageItem.instruction}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </h:form>
        </ui:define>
    </ui:composition>
</body>
</html>

production-assistant/web/ProjectView.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:define name="title">
        <h:outputText value="Проект"></h:outputText>
    </ui:define>
    <ui:composition template="./template.xhtml">
        <ui:define name="content">  
            <f:metadata>
                <f:viewParam name="idProject" value="#{projectViewController.idProject}" />
            </f:metadata>
            <h3>
                <h:panelGrid id="projectInfoGrid" columns="2" style="margin-bottom:10px">
                    <h:outputText value="Проект:" /> <h:outputText value="#{projectViewController.current.idProject}" />  
                    <h:outputText value="Исполнитель:" /> <h:outputText value="#{projectViewController.current.idExecutor.fullName}" />  
                    <h:outputText value="Состояние проекта:" /> <h:outputText value="#{projectViewController.current.idProjectstate.name}" />  
                    <h:outputText value="Дата начала:" /> <h:outputText value="#{projectViewController.current.dbegin}" />  
                    <h:outputText value="Дата завершения:" /> <h:outputText value="#{projectViewController.current.dend}" />  
                    <h:outputText value="Комментарий:" /> <h:outputText value="#{projectViewController.current.comment}" />  
                    <p:commandButton value='Изменить' oncomplete="editProjectDialogVar.show();" />
                </h:panelGrid>  
            </h3>
            <p:dialog id="editProjectDialog" widgetVar="editProjectDialogVar" modal="true">
                <h:form>
                    <h:panelGrid columns="2" style="margin-bottom:10px">
                        <h:outputText value="Состояние проекта:" />
                        <h:selectOneMenu  value="#{projectViewController.current.idProjectstate}" required="true">  
                            <f:selectItems value="#{projectstateController.items}" var="item" itemLabel="#{item.name}" itemValue="#{item}"/>  
                        </h:selectOneMenu>  
                        <h:outputText value="Исполнитель" />
                        <h:selectOneMenu  value="#{projectViewController.current.idExecutor}" required="true">  
                            <f:selectItems value="#{personController.items}" var="item" itemLabel="#{item.fullName}" itemValue="#{item}"/>  
                        </h:selectOneMenu>  
                        <h:outputText value="Комментарий:" /> <p:inputText value="#{projectViewController.current.comment}" />  
                    </h:panelGrid>
                    <p:commandButton action='#{projectViewController.update}' value='ОК'  process='@form' update=':projectInfoGrid' oncomplete='editProjectDialogVar.hide();' />
                </h:form>
            </p:dialog>


            <p:tabView id="projectTab">
                <p:tab id="entityProject" title="Сборки">
                    <p:commandButton id="addLinkageButton" type="button" value="Добавить сборку" onclick="dlgLinkage.show();" /> 
                    <p:dialog header="Добавить сборку в проект" widgetVar="dlgLinkage" resizable="false" modal="true" width="1000" height="700">  
                        <h:form id="dlgForm">    
                            <p:inputText value="#{linkageController.name}" />  
                            <p:commandButton  action='#{linkageController.setParameters}' process="@this" value='Искать'  update="searchLinkage"/>
                            <p:dataTable id="searchLinkage" var="item" value="#{linkageController.items}"  scrollable="true" >  
                                <p:column headerText="Наименование сборки" width="150">  
                                    <h:outputText value="#{item.name}" />  
                                </p:column>     
                                <p:column headerText="Инструкция" width="200">  
                                    <h:outputText value="#{item.instruction}" />  
                                </p:column>  
                                <p:column headerText="Действия" >  
                                    <p:commandButton action="#{linkageController.copyIntoProject(projectViewController.current.idProject)}" process="@this" update=":projectTab:linkageItem" value="Скопировать в проект" >
                                        <f:actionListener binding="#{projectViewController.update()}"/>
                                    </p:commandButton>
                                </p:column>  
                            </p:dataTable>  
                            <p:commandButton value="ОК" id="submitButton"  process="@this" update=":projectTab:linkageItem, :projectTab:wrappingItemFree" oncomplete="dlgLinkage.hide();" />  
                        </h:form>    
                    </p:dialog>
                    <p:dataTable id="linkageItem" var="linkageItem"  value="#{projectViewController.current.linkageCollection}">
                        <p:column headerText="Наименование">
                            <h:outputText value="#{linkageItem.name}" />
                        </p:column>
                        <p:column headerText="Инструкция">
                            <h:outputText value="#{linkageItem.instruction}" />
                        </p:column>
                        <p:column headerText="Действия">  
                            <p:commandButton action='#{linkageController.destroy(linkageItem)}' process="@this" update=":projectTab:linkageItem, :projectTab:wrappingItemFree" value='Удалить'>
                                <f:actionListener binding="#{projectViewController.removeLinkage(linkageItem)}"/>
                            </p:commandButton>
                        </p:column>  
                    </p:dataTable>
                </p:tab>

                <p:tab id="wrappingProject" title="Упаковки">
                    <p:dialog header="Добавить упаковку" widgetVar="dlgWrapping" resizable="false" modal="true" width="200" height="200" dynamic="true" >  
                        <h:form id="dlgFormWrapping">    
                            <p:inputText value="#{wrappingController.wrapping.no}" />  
                            <p:commandButton value="ОК" action="#{wrappingController.createWrapping()}" process="@form" update=":projectTab:wrappingItem"/>  
                        </h:form>    
                    </p:dialog>

                    <p:dialog header="Добавить деталь" widgetVar="dlgAddPart" resizable="false" modal="true" width="300" height="200" dynamic="true">  
                        <h:form id="dlgFormWrapping1">    
                            <h:panelGrid columns="2" style="margin-bottom:10px">
                                <h:outputText value="Деталь " />
                                <h:selectOneMenu id="oneMenu" value="#{wrappingController.partAddToWrapping}"  required="true" >  
                                    <f:selectItem itemLabel="Деталь" itemValue=""/>  
                                    <f:selectItems value="#{wrappingController.wrappingFreeItems}" var="item" itemLabel="#{item.key.code}" itemValue="#{item.key.idPart}"/>  
                                    <p:ajax  process="oneMenu"   update="minmax" event="change" />
                                </h:selectOneMenu>  
                                <h:outputText value="Количество: " />
                                <p:spinner id="minmax"   
                                           value="#{wrappingController.partAddToWrappingCount}" min="1" max="#{wrappingController.partAddToWrappingCountMax}" readonly="#{wrappingController.partAddToWrapping==null?true:false}"/>  
                            </h:panelGrid>
                            <p:commandButton value="ОК" action="#{wrappingController.addPartToWrapping()}" process="@form" update=":projectTab:wrappingItem, :projectTab:wrappingItemFree, :projectTab:dlgFormWrapping1" />  
                        </h:form>    
                    </p:dialog>

                    <p:dataTable id="wrappingItemFree" var="wrappingItem1" value="#{wrappingController.wrappingFreeItems}" >
                        <p:column headerText="Наименование детали" >
                            #{wrappingItem1.key.code}
                        </p:column>
                        <p:column headerText="Остаток" >
                            #{wrappingItem1.value}
                        </p:column>
                    </p:dataTable>
                    <p:dataTable id="wrappingItem" var="wrappingItem" value="#{wrappingController.wrappingItems}" >
                        <p:column>
                            <p:dataTable var="parts" value="#{wrappingItem.wrappingpartCollection}">  
                                <f:facet name="header">  
                                    Упаковка № #{wrappingItem.no}   
                                    <p:commandButton action="#{wrappingController.deleteWrapping()}" update=":projectTab:wrappingItem, :projectTab:wrappingItemFree, :projectTab:dlgFormWrapping1" value='Удалить'/>
                                    <p:commandButton action="#{wrappingController.prepareAddPartToWrapping()}" update=":projectTab:wrappingItem, :projectTab:wrappingItemFree" value='Добавить деталь'/>
                                </f:facet>  
                                <p:column>  
                                    #{parts.idPart.code}  
                                </p:column>  
                                <p:column>  
                                    #{parts.countElement}  
                                </p:column>  
                                <p:column>  
                                    <p:commandButton action="#{wrappingController.deletePartFromWrapping(parts)}" update=":projectTab:wrappingItem, :projectTab:wrappingItemFree, :projectTab:dlgFormWrapping1" value='Удалить'/>
                                </p:column>  
                            </p:dataTable>  
                        </p:column>

                    </p:dataTable>

                    <h:form>
                        <p:commandButton id="addWrappingButton" action="#{wrappingController.prepareCreateWrapping}" value="Добавить упаковку" /> 
                    </h:form>

                </p:tab>
            </p:tabView>
            <h:form>
                <p:commandButton id="executeReport" actionListener="#{projectViewController.executeReport}" value="Отчет" ajax="false"/>
            </h:form>
        </ui:define>
    </ui:composition>
</html>